### ISSUE TITLE
被关联对象BindEntity是否支持只查询部分字段

### ISSUE THREAD

**Issue by ivancxj** [dromara/mybatis-plus-ext#1]
目前BindEntity 对象支持设置JoinCondition,orderBy,customCondition, last。
能否增加一个 select(查询被关联表的部分字段，目前是查询所有字段)

**Comment by imtzc** [comment]
可以，加入下一个版本计划

**Comment by imtzc** [comment]
@ivancxj 如果只是一两个字段，可以考虑使用BindField

**Comment by ivancxj** [comment]
> @ivancxj 如果只是一两个字段，可以考虑使用BindField

BindField目前只支持一个字段。
或者可以在Binder.bind 支持传参select columns也可以，这样可以用SFunction<T, ?>... columns。这个你评估决定哈

**Comment by imtzc** [comment]
@ivancxj 忘记通知你了，在后续的版本中我已经在@BindEntity与@BindEntityByMid中添加了selectFields属性，这个issues我就关闭啦
