### ISSUE TITLE
被关联对象如何指定数据源

### ISSUE THREAD

**Issue by waterzmh** [dromara/mybatis-plus-ext#2]
调用Binder.bind()，发现被关联对象又使用了默认数据源。
被关联类model使用注解:
@Table(
    dsName = "xxx"
)
发现未生效，没有连接到指定数据源xxx

**Comment by imtzc** [comment]
@Table(
dsName = "xxx"
)
的本意，仅限于构件表的场景，你的意思是被bind的类上标注了与主类不同的数据源，然后希望被关联查询的时候自动切换数据源么？
这个目前的确没有支持，可以考虑支持下，另外，如果你现在要解决这个问题，可以在被关联的实体对应的Mapper上使用数据源切换注解进行切换

**Comment by imtzc** [comment]
> 调用Binder.bind()，发现被关联对象又使用了默认数据源。 被关联类model使用注解: @table( dsName = "xxx" ) 发现未生效，没有连接到指定数据源xxx
如上

**Comment by waterzmh** [comment]
两个类都是同一个数据源b,程序的默认数据源是a，
使用上主类确实使用了数据源b,被关联的类使用了数据源a,两个类的mapper上都使用了注解@DS(xxx)

**Comment by imtzc** [comment]
好的，非常感谢提交问题，我确认下问题，尽快本周在下个版本进行修复

**Comment by imtzc** [comment]
@waterzmh 请关注版本3.5.5-EXT650
